@c $Id: distribution.texi,v 45.0 1997/09/19 05:42:02 jthomas Exp $
@c Copyright (C) 1994, The University of Texas at Austin.

@node Distribution, Installation, Agreement, Top
@chapter Distribution

The P2 program and manuals can be retrieved via anonymous ftp.
@xref{Installation}.

CONTACT INFORMATION:

@display
Don Batory
University of Texas at Austin
Department of Computer Science
Taylor Hall 2.124
Austin TX 78712.

@code{dsb@@cs.utexas.edu}
@end display
