/* $Id: P2_mmap.h,v 45.1 1997/09/29 03:50:08 jthomas Exp $ */
/* Copyright (C) 1997, The University of Texas at Austin. */

#ifndef INCLUDE_P2_MMAP_H
#define INCLUDE_P2_MMAP_H

/* P2 will automatically #include this file in every file.  Thus, we
   want to #include as few additional files as possible in this file.
   We don't want to include P2_paces.h, which defines BOOLEAN, so
   we'll use int instead. (JAT) */

/*****************************************************************************/
/*                  Function prototypes.                                     */
/*****************************************************************************/

/* These routines are called from the code generated by
   paces/mmap_persistent.xp and paces/mmap_shared.xp,
   see paces/mmap.xp1. (JAT) */
/* These routines should not be called directly. (DSB) */

int P2_open_mmap_memory(const char *filename, int size_in_bytes,
                        int persistent, int f);
void P2_close_mmap_memory(int persistent, int f);
void P2_sync_mmap_memory(const void *addr, int len, int async, int f);

void *P2_open_mmap_var(const char *varname, int size_in_bytes, int *new, int f);
void P2_delete_mmap_var(const char *varname, int f);

int P2_mmap_overflow(int f);
int P2_mmap_varoverflow(int size_in_bytes, int f);

void *P2_mmap_alloc(int size_in_bytes, int f);
void P2_mmap_free(const void *v, int f);

#endif /* INCLUDE_P2_MMAP_H */
