/* $Id: P2_op-vec-manager.h,v 45.0 1997/09/19 05:42:37 jthomas Exp $ */
/* Copyright (C) 1997, The University of Texas at Austin. */

#ifndef INCLUDE_P2_OP_VEC_MANAGER_H
#define INCLUDE_P2_OP_VEC_MANAGER_H

/*****************************************************************************/
/*                  Includes.                                                */
/*****************************************************************************/

#include "op-id.h"          /* P2_MAX_OP_ID */
#include "print-log.h"      /* P2_PRINT_LOG */
#include "P2_log-manager.h" /* P2_CURS_ID */

/*****************************************************************************/
/*                  Typedefs.                                                */
/*****************************************************************************/

/* Array of pointers to functions: special operations which been
   proceduralized by the layer x/init_generic.xp */
typedef int (**P2_OP_VEC)();

/* Operation name vector. */
typedef char P2_OP_NAME_VEC[P2_MAX_OP_ID][100];

/*****************************************************************************/
/*                  Function prototypes.                                     */
/*****************************************************************************/

/* These routines are called from the code generated by recovery.xp */
/* These routines should not be called directly. (JAT) */

void           P2_init_op_vec_manager(void);
void           P2_delete_op_vec_manager(void);
P2_OP_VEC      P2_get_op_vec(P2_CURS_ID id);

#if defined(P2_PRINT_LOG)
P2_OP_NAME_VEC *P2_get_op_name_vec(P2_CURS_ID id);
void           P2_put_op_vec(P2_CURS_ID id, P2_OP_VEC op_vec,
                             P2_OP_NAME_VEC op_name_vec);
#else
void           P2_put_op_vec(P2_CURS_ID id, P2_OP_VEC op_vec);
#endif /* P2_PRINT_LOG */

#endif /* INCLUDE_P2_OP_VEC_MANAGER_H */
