
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 116
#define YY_END_OF_BUFFER 117
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[444] =
    {   0,
        0,    0,  117,  115,    3,    1,   84,  115,  115,   92,
       86,   80,  115,   68,   69,   76,   81,   70,   82,   75,
       85,   64,   64,   77,   78,   87,   79,   88,   91,   63,
       63,   63,   73,   74,   89,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   71,   90,   72,   83,    3,  101,    0,   67,
        0,    0,    4,  107,  102,  112,    0,   66,    0,  105,
       94,  108,   95,  109,   93,    0,    2,  106,   65,   64,
        0,    0,   64,   64,    0,   64,   64,   64,   64,   64,
       64,   64,   96,   98,  100,   99,   97,   63,    0,    0,

       63,  113,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   15,   63,   63,   63,   63,   63,   63,   63,   63,
       23,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,  114,  103,  104,    2,
       65,    0,   65,    0,   65,   64,   64,   64,   64,   64,
      110,  111,   63,   63,   63,   63,   63,   63,   63,   63,
       63,    5,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   21,   63,   63,
       63,   63,   24,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,    0,   65,   64,   64,   64,
       64,   64,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,    7,   63,    9,   10,   63,   63,
       63,   63,   63,   63,   63,   63,   17,   18,   63,   63,
       63,   63,   63,   22,   63,   27,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   40,   63,   63,   63,   64,   64,   64,
       63,   63,   63,    5,   63,   63,   63,   63,   63,   63,
       63,   63,    8,   63,   12,   63,   63,   63,   63,   63,
       63,   63,   63,   20,   63,   63,   53,   63,   63,   63,

       63,   63,   63,   30,   63,   63,   63,   63,   63,   63,
       63,   63,   38,   63,   61,   63,   63,   62,   42,   64,
       64,   64,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   46,   63,   63,
       16,   63,   19,   63,   63,   25,   63,   63,   29,   63,
       56,   31,   32,   33,   63,   34,   35,   63,   37,   63,
       63,   63,   63,   59,   63,   63,   12,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   14,   63,   48,   49,
       63,   54,   63,   55,   63,   36,   63,   11,   63,   63,
       60,   63,   63,   25,   63,   31,   63,   63,   63,   44,

       63,   13,   63,   50,   63,   28,   63,   39,   41,   63,
       63,   63,   26,   63,   63,   63,   43,   45,   63,   63,
       57,   58,   63,   41,   47,   63,   63,    6,   63,   63,
       63,   63,   63,   63,    6,   63,   63,   63,   52,   63,
       63,   51,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       23,   23,   23,   23,   23,   25,   25,   26,   27,   28,
       29,   30,   31,    1,   32,   32,   32,   32,   33,   34,
       35,   35,   35,   35,   35,   36,   35,   35,   35,   37,
       35,   35,   35,   35,   38,   35,   35,   39,   35,   35,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   35,   54,   55,   56,   57,
       58,   59,   35,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    4,    4,    4,    4,    4,    1,
        1,    1,    1,    4,    3,    3,    3,    3,    3,    3,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[450] =
    {   0,
        0,    0,  637,  638,   71,  638,  607,   66,  632,  638,
      605,   66,   67,  638,  638,  604,   62,  638,   63,  612,
       60,   89,  136,  638,  638,   55,  602,   56,  638,    0,
       86,  606,  638,  638,  600,  584,   27,  567,   52,   38,
       63,   43,   68,   66,  568,  565,   75,   83,  557,  566,
       61,  570,  638,   71,  638,  638,  145,  638,  123,  638,
      618,  617,  638,  638,  638,  638,  121,  638,  616,  638,
      638,  638,  638,  638,  638,  598,    0,  638,  143,   66,
      158,  178,  171,  172,    0,  173,  177,    0,  179,  197,
      186,  204,  588,  638,  638,  638,  587,    0,  129,  130,

      571,  638,  203,  107,  552,  564,  551,  566,   46,  550,
       92,  546,  126,  545,  545,  548,  545,  547,  539,  540,
        0,   84,  544,  552,  122,  549,  546,  539,   89,  171,
      543,  536,  133,  163,  135,  190,  638,  638,  638,    0,
      238,  256,  638,  260,  267,  192,  221,  261,  253,  262,
      638,  638,  207,  183,  536,  536,  547,  538,  523,  531,
      539,    0,  529,  541,  536,  524,  524,  215,  521,  536,
      533,  533,  522,  528,  520,  526,  529,  524,  523,  522,
      512,  516,    0,  517,  518,  513,  502,  515,  514,  502,
      504,  511,  497,  498,  494,  494,  506,  496,  500,  499,

      504,  502,  504,  488,  492,  282,  296,  312,  276,  305,
      295,  307,  498,  500,  477,  487,  480,  484,  485,  493,
      487,  478,  481,  478,    0,  480,    0,    0,  486,  470,
      255,  473,  467,  480,  473,  478,    0,    0,  466,  463,
      479,  463,  465,    0,  464,    0,  460,  458,  458,  472,
      460,  453,  465,  455,  459,  462,  463,  462,  265,  451,
      456,  458,  453,    0,  442,  454,  453,  330,  293,  312,
      446,  438,  440,  454,  437,  435,  442,  445,  436,  443,
      446,  442,    0,  426,    0,  435,  430,  426,  430,  427,
      434,  425,  424,    0,  433,  426,    0,  429,  431,  414,

      418,  427,  428,    0,  424,  421,  423,  421,  406,  415,
      417,  415,    0,  407,    0,  418,  409,    0,    0,    0,
      319,  332,  409,  408,  410,  414,  404,  394,  398,  399,
      404,  394,  389,  397,  389,  391,  384,    0,  384,  397,
        0,  382,    0,  391,  395,    0,  374,  391,    0,  387,
        0,    0,    0,    0,  394,    0,    0,  387,    0,  387,
      375,  379,  380,    0,  366,  385,  386,  380,  384,  379,
      376,  372,  367,  362,  373,  372,    0,  367,    0,  365,
      374,    0,  357,    0,  371,    0,  367,    0,  365,  354,
        0,  342,  353,  350,  349,  348,  347,  335,  338,    0,

      328,    0,  330,    0,  339,    0,  323,    0,    0,  321,
      317,  334,    0,  333,  332,  326,    0,    0,  323,  309,
        0,    0,  324,  327,    0,  312,  303,  315,  309,  288,
      266,  271,  251,  210,    0,  198,  187,  181,    0,  165,
      136,    0,  638,  395,  399,  403,  405,  409,  186
    } ;

static yyconst flex_int16_t yy_def[450] =
    {   0,
      443,    1,  443,  443,  443,  443,  443,  444,  445,  443,
      443,  443,  446,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  447,
      447,  447,  443,  443,  443,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  443,  443,  443,  443,  443,  443,  444,  443,
      444,  445,  443,  443,  443,  443,  446,  443,  446,  443,
      443,  443,  443,  443,  443,  443,  448,  443,  443,   22,
      443,  443,  443,  443,  449,  443,  443,   23,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  447,  444,  446,

      447,  443,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  443,  443,  443,  448,
      443,  443,  443,  443,  443,  443,  443,  449,  443,  443,
      443,  443,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  443,  443,  148,  443,  443,
      443,  443,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  208,  443,  443,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  148,
      443,  443,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,

      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,    0,  443,  443,  443,  443,  443,  443
    } ;

static yyconst flex_int16_t yy_nxt[711] =
    {   0,
        4,    5,    6,    5,    5,    5,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   23,   23,   24,   25,   26,   27,   28,
       29,   30,   30,   30,   30,   31,   32,   30,   30,   33,
        4,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   30,   44,   30,   45,   30,   30,   46,   30,   47,
       48,   49,   50,   51,   52,   30,   30,   30,   53,   54,
       55,   56,   57,   60,   57,   57,   57,   65,   71,   68,
       77,   73,   93,   94,   96,   97,  111,  104,   78,  105,
       72,   74,   75,   99,   66,  112,  107,  116,  100,  137,

      117,  167,  168,  108,  443,  134,   61,   69,   79,  109,
       80,   80,   80,   81,  110,  121,  118,  113,  135,  114,
      119,   82,  122,  125,   83,  120,   84,   85,  115,  127,
       60,  443,  126,   68,  128,  129,   60,   82,  182,  191,
      138,  170,   68,   86,  130,  183,   57,  131,   57,   57,
       57,   87,  171,  161,   85,   79,  192,   88,   88,   88,
       88,   69,  162,   61,  141,  141,  141,  141,   82,   61,
       69,   89,  186,   90,  173,  142,  143,   79,  143,   81,
       81,   81,   81,  187,   82,  198,  174,  202,  148,  203,
       91,  142,  143,  199,  144,  442,  144,  143,   92,  145,

      145,  145,  145,   82,   82,   82,  146,  147,  146,   82,
      146,   82,  146,  441,  149,  193,  149,  200,   82,   82,
       82,   82,  201,  149,   82,   82,  146,   82,  194,   82,
      195,  146,  150,  146,   82,  146,   82,  440,  204,  149,
       82,  149,  205,  216,  217,   82,  439,  154,  149,  155,
      438,  149,   82,   82,  213,  156,  146,  157,  149,  141,
      141,  141,  141,  158,  159,  214,  160,  437,  215,   82,
      142,  143,  206,  143,  206,  230,  231,  207,  207,  207,
      207,  145,  145,  145,  145,   82,  142,  143,  145,  145,
      145,  145,  143,  208,   82,  436,  209,  149,  210,  286,

      143,   82,  143,  207,  207,  207,  207,  287,   82,  208,
       82,  269,  311,  269,  435,  211,  143,  207,  207,  207,
      207,  143,  312,  212,   82,   82,  434,   82,  144,  143,
      144,  143,  269,  268,  268,  268,  268,   82,  269,   82,
      270,   82,  269,   82,   82,  143,  443,  269,  443,  433,
      143,   82,  409,   82,  269,   82,  269,  269,  432,  269,
       82,  269,  431,  320,   82,  321,  426,   82,  430,  269,
      429,  427,  428,  425,  424,  359,  352,  346,  423,  320,
       82,  269,  422,  421,  322,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  269,   59,  285,   59,   59,   62,

       62,   62,   62,   67,  411,   67,   67,   98,   98,  140,
      410,  140,  140,  409,  408,  407,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  162,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,

      323,  319,  318,  317,  316,  315,  314,  313,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  197,  196,  190,  189,  188,  185,

      184,  181,  180,  179,  178,  177,  176,  175,  172,  169,
      166,  165,  164,  163,  153,  152,  151,  139,   67,   63,
       59,  136,  133,  132,  124,  123,  106,  103,  102,  101,
       95,   76,   70,   64,   63,   58,  443,    3,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443
    } ;

static yyconst flex_int16_t yy_chk[711] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    8,    5,    5,    5,   12,   17,   13,
       21,   19,   26,   26,   28,   28,   40,   37,   21,   37,
       17,   19,   19,   31,   12,   40,   39,   42,   31,   54,

       42,  109,  109,   39,   80,   51,    8,   13,   22,   39,
       22,   22,   22,   22,   39,   44,   43,   41,   51,   41,
       43,   22,   44,   47,   22,   43,   22,   22,   41,   48,
       59,   80,   47,   67,   48,   48,   99,   22,  122,  129,
       54,  111,  100,   22,   48,  122,   57,   48,   57,   57,
       57,   22,  111,  104,   22,   23,  129,   23,   23,   23,
       23,   67,  104,   59,   79,   79,   79,   79,   23,   99,
      100,   23,  125,   23,  113,   79,   79,   81,   79,   81,
       81,   81,   81,  125,   23,  133,  113,  135,  449,  135,
       23,   79,   79,  133,   82,  441,   82,   79,   23,   82,

       82,   82,   82,   83,   84,   86,   83,   84,   83,   87,
       86,   89,   87,  440,   89,  130,   89,  134,   91,   83,
       84,   86,  134,   91,  146,   87,   84,   89,  130,   90,
      130,   87,   90,   83,   91,   86,   92,  438,  136,   92,
      146,   89,  136,  154,  154,   90,  437,  103,   91,  103,
      436,   90,   92,  147,  153,  103,  147,  103,   92,  141,
      141,  141,  141,  103,  103,  153,  103,  434,  153,  147,
      141,  141,  142,  141,  142,  168,  168,  142,  142,  142,
      142,  144,  144,  144,  144,  149,  141,  141,  145,  145,
      145,  145,  141,  148,  150,  433,  148,  150,  148,  231,

      145,  149,  145,  206,  206,  206,  206,  231,  209,  148,
      150,  209,  259,  209,  432,  148,  145,  207,  207,  207,
      207,  145,  259,  148,  209,  269,  431,  211,  208,  207,
      208,  207,  211,  208,  208,  208,  208,  210,  209,  212,
      210,  269,  212,  211,  270,  207,  268,  270,  268,  430,
      207,  321,  429,  210,  321,  212,  321,  211,  428,  210,
      270,  212,  427,  268,  322,  268,  420,  321,  426,  322,
      424,  420,  423,  419,  416,  415,  414,  412,  411,  268,
      322,  321,  410,  407,  268,  405,  403,  401,  399,  398,
      397,  396,  395,  394,  322,  444,  393,  444,  444,  445,

      445,  445,  445,  446,  392,  446,  446,  447,  447,  448,
      390,  448,  448,  389,  387,  385,  383,  381,  380,  378,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  363,  362,  361,  360,  358,  355,  350,  348,
      347,  345,  344,  342,  340,  339,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  317,  316,  314,  312,  311,  310,  309,  308,  307,
      306,  305,  303,  302,  301,  300,  299,  298,  296,  295,
      293,  292,  291,  290,  289,  288,  287,  286,  284,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,

      271,  267,  266,  265,  263,  262,  261,  260,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      245,  243,  242,  241,  240,  239,  236,  235,  234,  233,
      232,  230,  229,  226,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  167,  166,  165,  164,  163,  161,  160,  159,
      158,  157,  156,  155,  132,  131,  128,  127,  126,  124,

      123,  120,  119,  118,  117,  116,  115,  114,  112,  110,
      108,  107,  106,  105,  101,   97,   93,   76,   69,   62,
       61,   52,   50,   49,   46,   45,   38,   36,   35,   32,
       27,   20,   16,   11,    9,    7,    3,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pb-lex.l"
#line 2 "pb-lex.l"
/* Generated automatically from pb-lex.l.in by Makefile. */
#line 11 "pb-lex.l"

/* $Id: pb-lex.l.in,v 45.0 1997/09/19 05:45:55 jthomas Exp $ */
/* Copyright (C) 1997, The University of Texas at Austin. */

/* pb lexicographic analyzer (flex source file). */

/*

Derived from a source file by James A. Roskind (1990)
Original comments are retained for documentation purposes (DSB).

PREDATOR additions by JAT.

*/

/*

Comment  removal  must  be done during the lexing, as context (such as
enclosure in string literals) must be  observed.   For  this  cut-down
lexer,  we  will  assume that comments have been removed (don't assume
this if you are writing a compiler or browser!).

For each IDENTIFIER like string that is found,  there  are  several
distinct interpretations that can be applied:

1)  The  preprocessor  may  interpret  the  string as a "keyword" in a
directive (eg: "pragma" or "include", "defined").

2) The parser may interpret the string as a keyword. (eg: "int").

3) Both parser and preprocessor may interpret the string as a  keyword
(eg: "if").

Since  this  file  is based on source that actually lexically analyses
text for both preprocessing and parsing, macro definitions  were  used
throughout.   The macro definitions supplied here have been customized
to a C++ parse only, and  all  preprocessor  keywords  are  passed  as
IDENTIFIER  or  TYPEDEFname.   Also, since there is no symbol table to
interrogate to decide whether a string  is  a  TYPEDEFname,  I  simply
assume  that  any  identifier beginning with an upper case letter is a
TYPEDEFname.  This hack  should  allow  you  to  check  out  how  code
segments  are  parsed  using my grammar.  Unfortunately, if you really
want to parse major league code, you have to write a symbol table, and
maintain appropriate scoping information

(James  A.  Roskind).

*/

/************************************************************************/
/*              Includes.                                               */
/************************************************************************/

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>       /* NULL */
#include <string.h>      /* strcpy() */

#include "error.h"       /* parse_warning() */
#include "lex.h"         /* MAX_IDENT_LEN */
#include "op-tab.h"
#include "pb-type.h"
#include "util.h"
#include "xform.h"

#include "type.h"        /* NODE */
#include "pb-gram.tab.h" /* BISON-YACC generated defs based on C++ grammar */

/************************************************************************/
/*              YYLMAX.                                                 */
/************************************************************************/

/* Necessary for AT&T lex. */
#undef YYLMAX
#define YYLMAX MAX_IDENT_LEN

/************************************************************************/
/*              "Return" macros.                                        */
/************************************************************************/

/* Keyword. */

#define RETURN_KEYWORD_TOKEN(x) \
  RETURN_NODE_TOKEN(x, NULL)

/* Identifier. */

#define RETURN_IDENTIFIER_TOKEN() \
 RETURN_NODE_TOKEN((isaTYPE((char *) yytext)?TYPEDEFname:IDENTIFIER), NULL)

/* ASCII operator. */

#define RETURN_ASCII_OPERATOR_TOKEN(x) \
  RETURN_NODE_TOKEN(x, NULL)

/* Named, multi-character operator */

#define RETURN_NAMED_OPERATOR_TOKEN(x) \
  RETURN_NODE_TOKEN(x, NULL)

/* Constants. */

#define RETURN_CONSTANT_TOKEN(x, ctype) \
  RETURN_NODE_TOKEN(x, ctype)

/************************************************************************/
/*              Definitions.                                            */
/************************************************************************/
/* The following definitions are common to all P2 lex files. (JAT) */
/************************************************************************/
/*              Commands.                                               */
/************************************************************************/
#line 872 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 163 "pb-lex.l"



/* Some versions of flex define yywrap() as a macro.
   We define yywrap() as a function.
   Thus we must undefine yywrap(). (JAT) */

#undef yywrap


#line 1065 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 444 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 638 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 173 "pb-lex.l"
{ line_number++;
                      RETURN_WHITESPACE_TOKEN((char *) yytext);
                    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 176 "pb-lex.l"
{ RETURN_WHITESPACE_TOKEN(""); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 177 "pb-lex.l"
{ RETURN_WHITESPACE_TOKEN(""); }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 178 "pb-lex.l"
{ line_number++;
                      RETURN_WHITESPACE_TOKEN((char *) yytext);
                      ECHO;
                    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 183 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ASM); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 184 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ATTRIBUTE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 185 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(AUTO); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 186 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(BREAK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 187 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(CASE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 188 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(CHAR); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 189 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(VARCHAR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 190 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(CONST); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 191 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(CONTINUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 192 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(DEFAULT); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 193 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(DO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 194 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(DOUBLE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ELSE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 196 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ENUM); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 197 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(EXTERN); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 198 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(FLOAT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 199 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(FOR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 200 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(GOTO); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 201 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(IF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 202 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(INT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 203 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(INLINE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 204 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(LABEL); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 205 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(LONG); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 206 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(REGISTER); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 207 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(RETURN); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 208 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(SHORT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 209 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(SIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 210 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(SIZEOF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 211 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(STATIC); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 212 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(STRUCT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 213 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(SWITCH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 214 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(TYPEDEF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 215 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(TYPEOF); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 216 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(UNION); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 217 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(UNSIGNED); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 218 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(VOID); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 219 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(VOLATILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 220 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(WHILE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 222 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ASCENDING); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 223 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(COMPCURS); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 224 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(CONTAINER); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 225 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(CURSOR); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 226 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(DESCENDING); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 227 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ELEMENT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 228 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(FOREACH); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 229 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(FOREACHK); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 230 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(GENERIC_CONTAINER); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 231 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(GENERIC_CURSOR); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 232 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(GIVEN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 233 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ORDERBY); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 234 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(ROFEACH); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 235 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(SCHEMA); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 236 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(STORED_AS); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 237 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(P2_DDLHINT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 238 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(P2_PATH); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 239 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(P2_TYPEX); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 240 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(VALID); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 241 "pb-lex.l"
{ RETURN_KEYWORD_TOKEN(WHERE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 243 "pb-lex.l"
{ RETURN_IDENTIFIER_TOKEN(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 245 "pb-lex.l"
{ RETURN_CONSTANT_TOKEN(INTEGERconstant,
                                            int_read_only_ctype); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 247 "pb-lex.l"
{ RETURN_CONSTANT_TOKEN(FLOATINGconstant,
                                            float_read_only_ctype); }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 250 "pb-lex.l"
{ RETURN_CONSTANT_TOKEN(CHARACTERconstant,
                                            char_read_only_ctype); }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 252 "pb-lex.l"
{ RETURN_CONSTANT_TOKEN(STRINGliteral,
                                            string_read_only_ctype); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 255 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(LP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 256 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(RP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 257 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(COMMA); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 258 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(LC); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 259 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(RC); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 260 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(LB); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 261 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(RB); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 262 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(DOT); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 263 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(STAR); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 264 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(COLON); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 265 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(SEMICOLON); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 266 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(ASSIGN); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 267 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(AND); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 268 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(PLUS); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 269 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(MINUS); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 270 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(NEGATE); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 271 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(NOT); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 272 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(DIV); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 273 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(MOD); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 274 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(LT); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 275 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(GT); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 276 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(XOR); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 277 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(PIPE); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 278 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(QUESTION); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 280 "pb-lex.l"
{ RETURN_ASCII_OPERATOR_TOKEN(DOLLAR); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 282 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(ARROW); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 283 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(INCR); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 284 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(DECR); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 285 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(LS); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 286 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(RS); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 287 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(LE); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 288 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(GE); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 289 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(EQ); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 290 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(NE); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 291 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(ANDAND); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 292 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(OROR); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 293 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(ELLIPSIS); }  
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 294 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(MULTassign); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 295 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(DIVassign); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 296 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(MODassign); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 297 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(PLUSassign); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 298 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(MINUSassign); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 299 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(LSassign); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 300 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(RSassign); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 301 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(ANDassign); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 302 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(ERassign); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 303 "pb-lex.l"
{ RETURN_NAMED_OPERATOR_TOKEN(ORassign); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 305 "pb-lex.l"
{ parse_warning(4, "unknown character ignored"); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 307 "pb-lex.l"
ECHO;
	YY_BREAK
#line 1741 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 444 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 444 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 443);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 307 "pb-lex.l"




